temporada-solo/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :properties

end

temporada-solo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

temporada-solo/app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                :integer          not null, primary key
#  title             :string
#  location          :string
#  area              :integer
#  description       :string
#  daily_rate        :decimal(, )
#  rooms             :integer
#  minimum_rent_days :integer
#  maximun_rent_days :integer
#  photo             :string
#  maximum_occupancy :integer
#  usage_rules       :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  property_type_id  :integer
#

class Property < ApplicationRecord
  belongs_to :property_type
end

temporada-solo/app/models/property_type.rb
# == Schema Information
#
# Table name: property_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PropertyType < ApplicationRecord
  has_many :properties
end

temporada-solo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

temporada-solo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

temporada-solo/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def new
    @property = Property.new
    @property_types = PropertyType.all
  end
end

temporada-solo/app/helpers/application_helper.rb
module ApplicationHelper
end

temporada-solo/app/helpers/home_helper.rb
module HomeHelper
end

temporada-solo/app/helpers/property_helper.rb
module PropertyHelper
end

temporada-solo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemporadaSolo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Cadastrar imóvel', new_property_path%>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

temporada-solo/app/views/properties/_property_details.html.erb
<dl class="">
  <dt>Título:</dt>
  <dd><%= @property.title %></dd>

  <dt>Localização:</dt>
  <dd><%= @property.location %></dd>

  <dt>Tipo do imóvel:</dt>
  <dd><%= @property.property_type.name %></dd>

  <dt>Area:</dt>
  <dd><%= @property.area %></dd>

  <dt>Quantidade de quartos:</dt>
  <dd><%= @property.rooms %></dd>

  <dt>Máximo de pessoas:</dt>
  <dd><%= @property.maximum_occupancy %></dd>

  <dt>Minimo de dias para locação:</dt>
  <dd><%= @property.minimum_rent_days %></dd>

  <dt>Máximo de dias para locação:</dt>
  <dd><%= @property.maximun_rent_days %></dd>

  <dt>Diária:</dt>
  <dd><%= @property.daily_rate %></dd>

  <dt>Foto:</dt>
  <dd><%= @property.photo %></dd>

  <dt>Descrição:</dt>
  <dd><%= @property.description %></dd>

  <dt>Regras de uso:</dt>
  <dd><%= @property.usage_rules %></dd>


</dl>

temporada-solo/app/views/properties/new.html.erb
<%= form_for @property do |f|%>
  <div class="form-group">
    <%= f.label :title, 'Título', class: 'control-label'%>
    <%= f.text_field :title%>
  </div>

  <div class="form-group">
    <%= f.label :location, 'Localização', class: 'control-label'%>
    <%= f.text_field :location%>
  </div>
  <div class="form-group">
    <%= f.label :property_type_id, 'Tipo do imóvel'  %>
    <%= f.collection_select(:property_type_id, @property_types, :id, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :area, 'Area', class: 'control-label'%>
    <%= f.text_field :area%>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Descrição', class: 'control-label'%>
    <%= f.text_field :description%>
  </div>

  <div class="form-group">
    <%= f.label :daily_rate, 'Diária', class: 'control-label'%>
    <%= f.text_field :daily_rate%>
  </div>

  <div class="form-group">
    <%= f.label :rooms, 'Quantidade de quartos', class: 'control-label'%>
    <%= f.number_field :rooms%>
  </div>

  <div class="form-group">
    <%= f.label :minimum_rent_days, 'Minimo de dias para locação', class: 'control-label'%>
    <%= f.number_field :minimum_rent_days%>
  </div>

  <div class="form-group">
    <%= f.label :maximun_rent_days, 'Máximo de dias para locação', class: 'control-label'%>
    <%= f.number_field :maximun_rent_days%>
  </div>

  <div class="form-group">
    <%= f.label :photo, 'Foto', class: 'control-label'%>
    <%= f.text_field :photo%>
  </div>

  <div class="form-group">
    <%= f.label :maximum_occupancy, 'Máximo de pessoas', class: 'control-label'%>
    <%= f.text_field :maximum_occupancy%>
  </div>

  <div class="form-group">
    <%= f.label :usage_rules, 'Regras de uso', class: 'control-label'%>
    <%= f.text_field :usage_rules%>
  </div>

<% end %>

temporada-solo/app/views/properties/show.html.erb
<%= render 'property_details'%>