my-cookbook/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  get '/recipes/search/', to: 'recipes#search', as: 'search_recipe'
  resources :recipes
  resources :cuisines , only: [:new, :show, :create]
  resources :recipe_types
  #get '/recipes/use/:id', to: 'recipes#use', as: 'use_recipe'
end

my-cookbook/app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: {
    message: "Você deve informar o nome da cozinha"
  }, uniqueness: {
    message: "Esta Cozinha já existe, não é necessario cadastrar"
  }
end

my-cookbook/app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title , presence: true
  validates :cook_time , presence: true
  validates :cuisine_id , presence: true
  validates :method , presence: true
  validates :ingredients , presence: true
  validates :recipe_type , presence: true
  validates :difficulty, presence: true
  validates :recipe_type_id, presence: true
  belongs_to :cuisine
  belongs_to :recipe_type
end

my-cookbook/app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

my-cookbook/app/models/remove.rb
class Remove < ApplicationRecord
end

my-cookbook/app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def new
    @cuisine = Cuisine.new
  end

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def index
    @cuisine = Cuisine.all
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:name))

    if @cuisine.save
      redirect_to cuisine_url @cuisine
    else
      if(@cuisine.errors.any?)
        @cuisine.errors.each do |attribute, message|
          flash[:error] = message
        end

      end
      redirect_to new_cuisine_url
    end
  end

end

my-cookbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @last_six_recipes = Recipe.last(6)
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end
end

my-cookbook/app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end
  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
        redirect_to recipe_type_url @recipe_type
    else
      flash[:error] = 'Você deve informar o nome do tipo de receita'
      render :new
    end
  end
end

my-cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
        redirect_to recipe_url @recipe
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash[:error] = 'Você deve informar todos os dados da receita'
      render :new
    end

  end

  def edit
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  def update

    if @recipe.update(recipe_params)
      redirect_to recipe_url @recipe
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash[:error] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  def destroy
    flash[:message] = 'Receita apagada com sucesso'
    @recipe.destroy
    redirect_to root_url
  end

  def search
    @recipes = Recipe.where(title: params[:title])
    if @recipes.empty?
      flash[:error] = 'Nehuma receita encontrada'
      redirect_to request.referer
    else
      render :results
    end
  end

  private
  def set_recipe
     @recipe = Recipe.find(params[:id])
   end

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cook_time,
                                   :cuisine_id, :ingredients,
                                   :method, :difficulty, :featured)

  end
end

my-cookbook/app/helpers/cuisine_helper.rb
module CuisineHelper
end

my-cookbook/app/helpers/cuisines_helper.rb
module CuisinesHelper
end

my-cookbook/app/helpers/recipe_type_helper.rb
module RecipeTypeHelper
end

my-cookbook/app/helpers/recipe_types_helper.rb
module RecipeTypesHelper
end

my-cookbook/app/helpers/recipes_helper.rb
module RecipesHelper
end

my-cookbook/app/views/cuisines/new.html.erb
<%= flash[:error] %>

<%= form_for @cuisine, html: {class: "form-horizontal"} do |form| %>
  <div class="form-group">
    <%= form.label :name, 'Nome', class: 'control-label'%>
    <%= form.text_field :name , class: 'form-control'%>
  </div>
    <div class="form-group">
    <%= form.submit 'Enviar' , class: 'form-control' %>
  </div>
<% end %>

my-cookbook/app/views/cuisines/show.html.erb
<h1 class="title"><%= @cuisine.name%></h1>
<hr>
<% if @cuisine.recipes.empty? == false %>
  <% @cuisine.recipes.each do |recipe| %>
  <ul class="list-group">
    <h1 class="sub-title">Titulo: <%= recipe.title %></h1>
    <li class="list-group-item">Receita: <%= recipe.recipe_type.name %></li>
    <li class="list-group-item">Cozinha: <%= recipe.cuisine.name %></li>
    <li class="list-group-item">Dificuldade: <%= recipe.difficulty %></li>
    <li class="list-group-item">Tempo de cozimento: <%= recipe.cook_time %> minutos</li>
  </ul>
  <% end %>
<% else %>
<h1>Nenhuma receita encontrada para este tipo de cozinha</h1>
<% end %>
<%= link_to 'Voltar', root_path, class: 'btn btn-default'%>
<%= link_to 'Enviar uma receita', new_recipe_path, class: 'btn btn-default'%>

my-cookbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <hr>
    <div class="row">
      <div class="col-md-2">

      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3">
            <%= link_to 'Voltar ao inicio', root_path , class: 'btn btn-primary btn-block'%>

          </div>
          <div class="col-md-3">
            <%= link_to 'Nova Cozinha', new_cuisine_path , class: 'btn btn-primary btn-block'%>

          </div>
          <div class="col-md-3">
            <%= link_to 'Nova Receita', new_recipe_path , class: 'btn btn-primary btn-block'%>

          </div>
          <div class="col-md-3">
            <%= link_to 'Novo tipo de Receita', new_recipe_type_path, class: 'btn btn-primary btn-block'%>

          </div>

        </div>

      </div>
      <div class="row">
        <div class="col-md-12">
            <%= flash[:error] %>
            <%= render partial: '/shared/buscar_receita' %>
        </div>
      </div>


    </div>
    <hr>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

my-cookbook/app/views/recipe_types/new.html.erb
<%= flash[:error] %>
<%= form_for @recipe_type do |form| %>
  <%= form.label :name, 'Nome'%>
  <%= form.text_field :name %>

  <%= form.submit 'Enviar' %>
<% end %>

my-cookbook/app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<h1 class="title">RECEITAS DESTE TIPO</h1>
<% if @recipe_type.recipes.empty?%>
  <h1>Nenhuma receita encontrada para este tipo de receitas</h1>
<% else %>
  <% @recipe_type.recipes.each do |recipe| %>
    <ul class="list-group">
      <h1 class="sub-title">Titulo: <%= recipe.title %></h1>
      <li class="list-group-item">Receita: <%= recipe.recipe_type.name %></li>
      <li class="list-group-item">Cozinha: <%= recipe.cuisine.name %></li>
      <li class="list-group-item">Dificuldade: <%= recipe.difficulty %></li>
      <li class="list-group-item">Tempo de cozimento: <%= recipe.cook_time %> minutos</li>
    </ul>
  <% end %>
<% end %>

<%= link_to 'Voltar', root_path, class: 'btn btn-default'%>
<%= link_to 'Enviar uma receita', new_recipe_path, class: 'btn btn-default'%>

my-cookbook/app/views/recipes/_form.html.erb
<%= flash[:error] %>
<%= form_for @recipe , html: {class: "form-horizontal"} do  |f|  %>
<div class="form-group">
  <%= f.label :title, 'Título' , class: 'control-label'%>
  <%= f.text_field :title , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :recipe_type_id , 'Tipo da Receita' , class: 'control-label'%>
  <%= f.collection_select(:recipe_type_id, @recipe_types, :id, :name, class: "form-control") %>
</div>
<div class="form-group">
  <%= f.label :cuisine_id , 'Cozinha' , class: 'control-label'%>
  <%= f.collection_select(:cuisine_id, @cuisines, :id, :name, class: "form-control") %>
</div>
  <div class="form-group">
  <%= f.label :difficulty, 'Dificuldade', class: 'control-label' %>
  <%= f.text_field :difficulty  , class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.label :cook_time, 'Tempo de Preparo' , class: 'control-label'%>
  <%= f.number_field :cook_time , class: 'form-control' %>
  </div>
<div class="form-group">
  <%= f.label :ingredients , 'Ingredientes', class: 'control-label'%>
  <%= f.text_field :ingredients , class: 'form-control' %>
  </div>
<div class="form-group">
  <%= f.label :method, 'Como Preparar' , class: 'control-label'%>
  <%= f.text_field :method , class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :featured, 'Destaque', class: 'control-label' %>
  <%= f.check_box :featured, class: 'checkbox' %>
</div>

<div class="form-group">
  <%= f.submit submit_text , class: 'form-control' %>
</div>
<% end %>

my-cookbook/app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: { submit_text: 'Salvar'} %>

my-cookbook/app/views/recipes/new.html.erb
<div class="row">
  <div class="col-md=2">

  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { submit_text: 'Enviar'} %>

  </div>

  <div class="col-md-2">

  </div>

</div>

my-cookbook/app/views/recipes/results.html.erb
<% @recipes.each do |recipe|%>
<hr>
  <h1><%= link_to recipe.title , recipe %></h1>
  <h3>Detalhes</h3>
  <p><%= recipe.recipe_type.name %></p>
  <p><%= recipe.cuisine.name %></p>
<% end %>

my-cookbook/app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>
<% if @recipe.featured? %>
  <%= image_tag 'star.png' %>
<% end %>
<%= link_to 'Voltar', root_path, class: 'btn btn-default'%>
<%= link_to 'Editar', edit_recipe_path %>

<%= link_to 'Apagar Receita', recipe_path , method: :delete %>

my-cookbook/app/views/shared/_buscar_receita.html.erb
<div>
  <%= form_tag("/recipes/search", method: "get") do %>
    <%= label_tag(:title, "Buscar receita") %>
    <%= text_field_tag(:title) %>
    <%= submit_tag("Buscar") %>
  <% end %>
</div>